// <auto-generated />
namespace Kursova.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddCombinedData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCombinedData));
        
        string IMigrationMetadata.Id
        {
            get { return "202404161820418_AddCombinedData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
